### ISSUE TITLE
Validaciones incorrectas en formulario para pacientes

### ISSUE THREAD

**Issue by Nidev-lab** [ProyectoFinal-Rc/RollingVeterinaria--Frontend#60]
## Proceso

1. Ingrese con permisos admin
2. Intento modificar los datos de un paciente
3. Las validaciones estan mal realizadas

## Resultado esperado

• Poder poner un apellido de mas de una palabra (Ej: De la Vega, Teran Vega.)

## Resultado actual

• No puedo ingresar 2 apellidos, ni una Raza de perro con 2 palabras, ni el nombre de mi mascota con minimo 2 palabras

## Captura

https://github.com/ProyectoFinal-Rc/RollingVeterinaria--Frontend/assets/53904695/66aa8eed-cdda-4df7-a07d-dbadfac7774c

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by MauricioSor** [comment]
- Corrección de validaciones en módulo Editar Paciente y Crear Paciente. El módulo completo se encuentra validado

https://github.com/ProyectoFinal-Rc/RollingVeterinaria--Frontend/assets/106267352/9042183e-c5dd-42ec-84bc-e82092c645d8

https://github.com/ProyectoFinal-Rc/RollingVeterinaria--Frontend/assets/106267352/2a16ab04-1cc7-4508-8494-5f3876979e01
