### ISSUE TITLE
Crear paciente no funciona

### ISSUE THREAD

**Issue by Nidev-lab** [ProyectoFinal-Rc/RollingVeterinaria--Frontend#61]
## Proceso

1. Ingreso a crear paciente con credenciales admin.
2. Cargo todos los campos y clickeo guardar.
3. El paciente no se crea.

## Resultado esperado

• Que el paciente se cree, y en caso de no hacerlo, que me explique el motivo de por que no se crea.

## Resultado actual

• El paciente no se crea, sin motivo alguno.

## Captura

https://github.com/ProyectoFinal-Rc/RollingVeterinaria--Frontend/assets/53904695/dc6b0915-0975-4b45-b531-c15b3bbd3304

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by MauricioSor** [comment]
- Corrección de mensaje de error al cargar un nuevo paciente (en el video de muestra se hizo fallar el módulo a propósito, para representar el camino de error). 

https://github.com/ProyectoFinal-Rc/RollingVeterinaria--Frontend/assets/106267352/f827759c-3c10-4e4b-94ae-1e20fe9435d8


- "Si bien el problema aparenta ser que se debe a errores internos en el servidor, corregimos y dejamos explicito que el error se produjo en la comunicación del servidor, pero como anteriormente las sugerencias relatan, el módulo de ingreso de paciente estuvo funcionando todo el tiempo, además se puede apreciar en la respuesta anterior, que funciona ese módulo #60 "
