### ISSUE TITLE
Sin validacion de campos en creacion de turnos

### ISSUE THREAD

**Issue by Nidev-lab** [ProyectoFinal-Rc/RollingVeterinaria--Frontend#62]
## Proceso

1. Ingrese sistema con credenciales admin
2. Voy al formulario de creacion de turnos.
3. Completo los campos con espacios. 
4. Me crea un turno con datos vacios.

## Resultado esperado

• Que el formulario este minimamente validado

## Resultado actual

• El formulario no valida

## Captura

https://github.com/ProyectoFinal-Rc/RollingVeterinaria--Frontend/assets/53904695/e7f62c23-7408-425b-aa74-e11322d7bdb1

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by MauricioSor** [comment]
- Corrección de validaciones para Crear Turno corregida. Módulo de Crear turno está validado y funcionando.
https://github.com/ProyectoFinal-Rc/RollingVeterinaria--Frontend/assets/106267352/34a4f969-be60-4a20-bb7e-801f8164680c
