### ISSUE TITLE
Formulario sin validacion

### ISSUE THREAD

**Issue by Nidev-lab** [ProyectoFinal-Rc/RollingVeterinaria--Frontend#63]
## Proceso

1. Ingrese al sistema con credenciales admin.
2. Ingreso al formulario para crear una publicacion.
3. Guardo la publicacion

## Resultado esperado

• Que los campos esten validados

## Resultado actual

• Los campos no estan validados 

## Captura

https://github.com/ProyectoFinal-Rc/RollingVeterinaria--Frontend/assets/53904695/ea9336ee-1098-44d3-afe1-7b011779b4cf

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by MauricioSor** [comment]
- Corrección de validaciones en publicación realizada: 
 

https://github.com/ProyectoFinal-Rc/RollingVeterinaria--Frontend/assets/106267352/6596e30f-f325-42c2-9259-f799813c8d27
