### ISSUE TITLE
Editar pacientes no funciona

### ISSUE THREAD

**Issue by Nidev-lab** [ProyectoFinal-Rc/RollingVeterinaria--Frontend#64]
## Proceso

1. Ingrese al sistema con cuenta admin
2. Cambie campos de un paciente (peso, especie, plan)
3. Clickee boton guardas
4. El modal comunica que se realizo exitosamente.
5. Validar si el paciente cambio.

## Resultado esperado

• Que el paciente muestre los datos que cambie actualizados

## Resultado actual

• No actualiza los datos del paciente

## Captura

https://github.com/ProyectoFinal-Rc/RollingVeterinaria--Frontend/assets/53904695/fe094a2c-d3e1-4a9f-8a29-ed113f706026

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by MauricioSor** [comment]
- Corrección de editarPaciente realizada. La edición se realiza correctamente
https://github.com/ProyectoFinal-Rc/RollingVeterinaria--Frontend/assets/106267352/0836e2b2-488c-40a3-bad2-04c64fe4c14f
